### ISSUE TITLE
Quitter l'application pendant qu'un son est en train de jouer empêche de l'arrêter par la suite

### ISSUE THREAD

**Issue by Jimvy** [TGLuis/Youpidapp#10]
Une fois le son lancé, il n'est plus possible de l'arrêter par la suite...

Par contre quand on fait ce que j'ai dit dans #9 , là il est toujours possible d'arrêter le son vu que l'activité principale reste active...

Une solution pourrait être de créer un service pour le MediaPlayer (ce qui permettrait de le placer dans la zone de notifications d'Android 😲) et de récupérer le mediaplayer actif à chaque lancement de la MainActivity.

**Comment by FrancoisDuchene** [comment]
A voir si c'est toujours le cas au vu des nouvelles màj

**Comment by FrancoisDuchene** [comment]
Retesté maintenant, quand on sort de l'app et qu'on revient, le bouton stop fonctionne toujours (il coupe le son).
Quand on sort de l'app et qu'on kill le processus, le son est arrêté automatiquement.

Du coup je pense que je peux close l'issue vue qu'à priori il n'y a plus de problème (on réouvre dans le cas contraire)
