### ISSUE TITLE
Fix crash on random

### ISSUE THREAD

**Issue by Jimvy** [TGLuis/Youpidapp#21]
Le bug de Gheysen...

Je pense avoir trouvé son origine : en gros le playRandom() essaie aussi de jouer le son "aaaadb.json", ce qui plante de manière évidente (⊙_⊙)？

**Comment by Jimvy** [comment]
Fun fact : ça a été résolu dans #15 par accident ^^

**Comment by FrancoisDuchene** [comment]
bon ben on a créé une issue en même temps #22, par contre j'ai trouvé d'autres irrégularités

**Comment by FrancoisDuchene** [comment]
> Fun fact : ça a été résolu dans #15 par accident ^^

ah j'ai testé avec la version 2.0, c'est peut-être dû à ça, faudra refaire des tests avec la màj (deuxième raison pour essayer de sortir la 2.1 asap)

**Comment by Jimvy** [comment]
Est-ce que le problème se manifeste aussi sur la dernière version master ?

**Comment by FrancoisDuchene** [comment]
je sais pas checker maintenant, faudra investiguer plus tard

**Comment by Jimvy** [comment]
Dans #22 t'as report le bug de Gheysen, ou t'as report un autre bug que t'as découvert entre-temps ?

**Comment by FrancoisDuchene** [comment]
le bug de Gheysen + un autre bug trouvé pendant que j'essayais de le reproduire sur d'autres boutons (par contre, si on continue de parler de cette issue, ça serait peut-être mieux de switch de conversation directement en-dessous de celle-là)
