### ISSUE TITLE
Crash lors de spam répétitifs + Mediaplayer qui stop

### ISSUE THREAD

**Issue by FrancoisDuchene** [TGLuis/Youpidapp#22]
# Crash lors de spam répétitifs sur des touches de sons
Remarqué sur trois appareils différents (entre autre un Xiaomi Redmi Pro 8 et un OnePlus10).
Quand on appuie de manière répétée (genre essayer de spammer comme un malade pendant plus d'1 minute environ), l'app crash directement.

Autre bug plus ou moins relaté mais non lié à un crash, c'est quand on spamme un autre bouton que le random mais avec un son long (plus que 5s par ex). Après 1 minute ou deux, le son se coupe (y a une popup "stop" qui apparait en bas qui signifie que media  player a stop), mais rejoue les sons joués après. Par contre si on recommence à spammer directement après, il continue à se bloquer régulièrement. 

Les boutons buzzbox ne crashent pas, mais c'est peut-être lié au fait que les sons sont plutôt court en comparaison de certains autres.

Je me demande si c'est pas lié à mediaplayer d'android directement. J'ai pas encore regardé quelle exception ça lançait, mais c'est peut-être la queue de mediaplayer qui est pleine ou un truc du genre.

Le fait que le son se coupe n'est pas dérangeant, par contre le fait que le bouton random crash est ennuyeux. Il faudrait investiguer ne serait-ce que pour éviter le crash.

**Comment by FrancoisDuchene** [comment]
Apparemment le crash aurait été fix par fixé par #15 , à vérifier (et vérifier que les autres bugs auraient aussi été corrigé par la même occasion)

**Comment by Jimvy** [comment]
Guess what, il y a apparemment un nombre limité de MediaPlaye (31 ?)r qui peuvent être présents en même temps 😂

**Comment by FrancoisDuchene** [comment]
Comme quoi lol ça doit être ça du coup

**Comment by Jimvy** [comment]
Fun fact : même en quittant l'application et en la killant, les toasts "Stop" continuent d'apparaitre en bas de l'écran, il faut aller force-kill l'application pour les faire disparaitre.

**Comment by TGLuis** [comment]
> Guess what, il y a apparemment un nombre limité de MediaPlaye (31 ?)r qui peuvent être présents en même temps
J'étais au courant, pourquoi vous croyez que je me suis cassé la tête pour faire des mediaPlayers qui sont réutilisés dans Discothèque? XD ça m'a bien soulé cette histoire de MediaPlayer, si vous trouvez une manière de faire mieux que la soluce actuelle, j'accepte et je merge mais je pense avoir atteint un niveau de ras le bol des mediaPlayers pour ma part.

**Comment by Jimvy** [comment]
Comme ça j'ai lu qu'il existe la classe SoundPool, mais elle n'arrive pas à jouer plus que 5 secondes par piste audio, je sais pas pourquoi ^^
EDIT : https://stackoverflow.com/questions/24011610/android-ogg-file-stops-playing-after-a-few-seconds bon ben rip SoundPool, va falloir le réimplémenter nous-même si on veut fix ça.

Sinon je pense que la limite ne se situe pas tellement dans le nombre de MediaPlayer mais plutôt dans le nombre de threads de décodage de fichiers audio dans le backend de MediaPlayer. Par exemple, avec "mettez_vos_masques" je sais jouer jusqu'à 30-34 sons puis après ça plante ; avec "regarder_nouvelles" je n'ai pas atteint de limite. La seule différence entre ces sons c'est :
-  leur longueur: 10 secondes pour "nouvelles", 14 pour "masques". Donc peut-être que "mettez_vos_masques" prend tellement de temps à être décodé que le backend dit "merde" à un moment. Pourtant quand on spam moins vite ça pose aussi problème, et le nombre de pistes concurrentes est constant peu importe la durée du son.
- le type de fichier : WAV pour "nouvelles", "MP3" pour "masques" et ceux qui durent plus longtemps. Pourtant "vaches_cochons_enfants" ne pose pas de problème quand on le spam.

Peut-être que mettre une limite au nombre de sons joués en parallèle pourrait régler le soucis (jouer 30 "Virus 2" en parallèle n'est pas un use case intéressant).

**Comment by FrancoisDuchene** [comment]
Mettre une limite de sons joués en parallèle me semble être une bonne idée, faudra faire des tests pour trouver une bonne valeur mais si ça peut éviter des crashs, je pense que ça peut être bien. On peut commencer à tester avec 40 puis tester en décrémentant.
Et tkt Luis on t'en veut pas de pas vouloir te prendre encore la tête avec mediaplayer :P

**Comment by FrancoisDuchene** [comment]
Ca n'a plus vraiment l'air de crash. Je vais close l'issue pour l'instant (pas beaucoup d'intérêt de fix)
