### ISSUE TITLE
Bouton random : tous les sons ou juste ceux de la liste ?

### ISSUE THREAD

**Issue by Jimvy** [TGLuis/Youpidapp#23]
Dans #15 , il avait été remarqué que le bouton random jouait n'importe quel son dans l'app, y compris des sons qui sont dans les autres fragments mais qui ne sont pas dans le fragment principal.
La PR avait décidé de retirer cette possibilité.

En parallèle, dans #21 et #22 , il a été remarqué qu'un crash survient sur la version 2.0 (Play Store latest) quand on "spam" le bouton random.
Après analyse, c'est parce que le bouton random jouait n'importe quel son dans l'application. Ou plutôt, n'importe quel fichier dans `res/raw/`, y compris le fichier `aaaadb.json` de la DB.
La correction de #15 a eu comme side-effect de corriger ce bug vu que la liste des sons randoms est comprise dans la DB elle-même.

Du coup, si on veut revenir à l'état précédent #15 du bouton random, il faudrait pouvoir jouer tous les sons de l'appli. Je vois 3 possibilités :

1. On change https://github.com/TGLuis/Youpidapp/blob/b1d1bad2b551532e3ff821b13e97168b6e29549e/app/src/main/java/lufra/youpidapp/Discotheque.kt#L31-L34 pour que on élimine de la liste le fichier `aaaadb.json`. Ou alors on ne sélectionne que les resources dont le nom de fichier se termine par `.wav`/`.mp3`
2. On met tous les sons dans le fichier `aaaadb.json` et on rajoute un attribut "hidden" pour les sons qu'on ne veut pas afficher dans la soundbox. Pour bien faire on pourrait refactor `Discotheque.kt` pour qu'il n'utilise plus le tableau `all` mais qu'il récupère dynamiquement les resources en se basant sur le nom (avec un cache) (oui j'aime bien fair ecompliqué).
3. On s'en fiche et on laisse tel que c'est maintenant : c'est probablement le plus logique.

Qu'en pensez-vous ?

**Comment by TGLuis** [comment]
3. pour moi, comme ça si on veut créer d'autres écran ou d'autres sons cachés/ easter eggs, on est pas encore embêté. Et ça reste simple. Plus c'est compliqué à faire évoluer et moins on aura envie de faire des maj de cette app.

**Comment by FrancoisDuchene** [comment]
Juste pour être sûr parce que je suis pas sûr d'avoir bien compris, la liste des sons chargés en mémoire dans le array ````private val all = HashMap<String, Int>()```` contient bien uniquement les sons qui sont indiqués dans *aaaadb.json* ?  Donc si on met un son dans le dossier **raw** mais qu'on modifie pas *aaaadb.json*, il n'est pas contenu dans ```all``` ?

**Comment by Jimvy** [comment]
Non, `all` contient tous les fichiers dans le dossier raw, y compris aaaadb.json.
C'est lorsque l'app lit le fichier aaaadb.json qu'elle détermine quels sons elle affiche dans le fragment principal.
