### ISSUE TITLE
EXTERMINATE BUTTON

### ISSUE THREAD

**Issue by FrancoisDuchene** [TGLuis/Youpidapp#27]
EXTERMINATE EXTERMINATE EXTERMINATE

comme discuté dans #25, je vois deux solutions:
- on fait une copie du mp3 "*piou*" qu'on renomme en "*exterminate*"
- on change la manière dont les boutons sont créés pour que le nom des boutons soit dissocié du nom des mp3, et on utilise la "base de donnée" pour mettre le nom des boutons (en ajoutant un nouveau champs par ex)

Obviously, la première solution c'est la solution de facilité, on peut faire ça tout de suite mais on garde un comportement qui n'est pas forcément bon (ex si on veut rajouter d'autres boutons custom) et on utilise de la place pour rien (vu que les deux mp3 seront stockés).
La deuxième prendra un peu plus de temps à être codé et à être intégré. @Jimvy tu t'étais proposé pour le faire ? (sans te brusquer hein)

**Comment by TGLuis** [comment]
3eme solution: On fait un buzzer exterminate à la place d'un bouton classique :)

**Comment by FrancoisDuchene** [comment]
Go faire le buzzer alors 🗡️

**Comment by FrancoisDuchene** [comment]
Buzzer fait dans 98a6cfba5c2cb22115f64b224270c72066717b35
