### ISSUE TITLE
Ajouter de nouveaux effets

### ISSUE THREAD

**Issue by FrancoisDuchene** [TGLuis/Youpidapp#31]
Il y a plusieurs effets audios que l'on a pas encore exploré, comme la réverbération ou bassBoost. Ca serait bien d'ajouter d'autres effects que aigu/grave (tjrs en cours d'ailleurs). Il faudra modifier légèrement la discothèque et les layouts des paramètres de son.

https://developer.android.com/reference/android/media/audiofx/AudioEffect

**Comment by TGLuis** [comment]
This is a duplicate. Ton commentaire aurait dû aller en dessous de l'issue #17 . Donc je close cette issue.

**Comment by FrancoisDuchene** [comment]
J'avais pas fait gaffe, my bad
