### ISSUE TITLE
Random crash happens with the Discotheque and the MainActivity

### ISSUE THREAD

**Issue by Jimvy** [TGLuis/Youpidapp#8]
At this line:

https://github.com/TGLuis/Youpidapp/blob/fde927346f95f1346e27836d13dc709dd648ae68/app/src/main/java/lufra/youpidapp/MainActivity.kt#L55

I sometimes get a NullPointerException, indicating that the reading type has probably been lost.

I don't know what triggers this, except that it happens when I'm running the app from IntelliJ and the previous process was probably killed before, so I think it is a problem of persistent state that is not really persistent.

**Comment by FrancoisDuchene** [comment]
Is it still relevant with the new code upgrade(s) ?

**Comment by Jimvy** [comment]
Ok, le problème est que quand on fait

https://github.com/TGLuis/Youpidapp/blob/fde927346f95f1346e27836d13dc709dd648ae68/app/src/main/java/lufra/youpidapp/Helper.kt#L51-L54

ben ça n'écrit pas dans le fichier de config avant qu'on quitte l'appli.

Du coup, j'imagine que le bug que j'ai parfois, c'est le fichier qui n'est pas sauvegardé correctement. Genre, il est créé, mais il est vide, et il est "initialisé" mais sans que l'écriture ait lieu.

**Comment by FrancoisDuchene** [comment]
Okay donc pour résoudre ça, je vois deux solutions:

1. Une **défensive**: On rajoute des gardes-fous dans le `GetConfigValue` pour qu'il ne renvoie pas null (et éviter les *NullPointerException*) et utiliser des **try catch** chaque fois qu'on appelle `GetConfigValue`. Avec cette solution, on garde le fait qu'on sauvegarde quand l'app est en pause (réduction utilisation disque dur), mais on perd la persistance des données.
2. Une **aggressive**: Dès qu'une valeur est changée, on l'enregistre sur le disque en faisant un *force-flush*. Ca augmente l'utilisation disque dur (ralentissement (?)) mais on garde la persistance des données.

Je suis plus favorable à la **deuxième solution** car la persistance des données me semble plus importante qu'un (possible) petit ralentissement dû à l'écriture de données.
