### ISSUE TITLE
La navigation du menu crée des fragments différents pour des interfaces identiques

### ISSUE THREAD

**Issue by Jimvy** [TGLuis/Youpidapp#9]
Mettons que je fasse la chose suivante:
1. J'ouvre l'appli.
2. Je joue un son suffisamment long.
3. J'ouvre le menu et je switch sur la buzzbox.
4. J'ouvre le menu et je "retourne" sur la soundbox.

Le bouton du son pressé précédemment n'est pas actif : en effet, c'est un autre fragment qui a été créé.
5. Je presse "back" pour revenir sur la buzzbox, puis encore "back" pour revenir sur le fragment original

Le bouton du son est bien actif car on est revenu à l'activité initiale.

Heureusement, les animateurs, adapteurs etc qui ont été créés dans un fragment sont supprimés lorsqu'on delete un fragment, au moins on n'a pas de NullPointerException qui viennent de nulle part.

Perso cette expérience utilisateur est un peu étrange : si j'ouvre un son et que je reviens sur la page principale, je m'attendrais à arriver sur la même page que celle que j'ai quitté, donc à voir les animations.

**Comment by FrancoisDuchene** [comment]
A voir si c'est toujours le cas au vu des nouvelles màj

**Comment by FrancoisDuchene** [comment]
J'ai retesté à l'instant, l'animation du bouton qui est assombri n'est toujours pas présente quand j'effectue tes étapes dans l'ordre que t'as donné. C'est le seul truc bizarre que je vois par contre, le son reste joué, c'est juste un bug visuel

**Comment by TGLuis** [comment]
Normalement, depuis le merge, il devrait plus y avoir ce bug visuel. T'es sûr que tu l'as vu avec la branche master?

**Comment by TGLuis** [comment]
This is solved, I am pretty sure! Will be reopened if I am wrong but I don't think so.
